---

- name: check
  hosts: localhost
  gather_facts: false
  vars:
    multiline:
      name1: value1
      name2: value2
    list:
      - a
      - b
  tasks:
    - debug: var=multiline

    - debug:
        msg: "{{ item }}"
      loop: "{{ list }}"

    - name: Show me what you got
      debug:
        msg: "My name is {{ item.key }}. The value is {{ item.value }}"
      with_dict: "{{ multiline }}"
      
    - name: file
      debug: var=item
      with_file:
        - "./config.xml"
      
    - name: Read xml element
      community.general.xml:
        path: config.xml
        xpath: /com.cloudbees.hudson.plugins.folder.Folder/actions/properties
        content: com.cloudbees.hudson.plugins.folder.properties.FolderCredentialsProvider_-FolderCredentialsProperty
      register: xmlresp
        
